[project]
name = "isayhey"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "cowsay>=6.1",
]

[project.scripts]
isayhey = "isayhey:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
